#ifndef MINIMIZATION_TYPE_ENUM_HPP
#define MINIMIZATION_TYPE_ENUM_HPP

enum MinimizationType {
    TOTAL_TIME_SPENT,
    TOTAL_DISTANCE_TRAVELED,
    MAX_TIME_SPENT,
    MAX_DISTANCE_TRAVELED
};

#endif